<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Concerns\HasUlids;

class Measurement extends Model
{
    use HasUlids;

    /** ULIDs are strings and not auto-incrementing */
    public $incrementing = false;
    protected $keyType = 'string';

    // Do NOT include 'id' here; it's auto-generated by HasUlids
    protected $fillable = ['device_id', 'metric', 'value', 'unit', 'recorded_at', 'payload'];

    protected $casts = [
        // Remove any 'ulid' casts — they don't exist
        'recorded_at' => 'datetime',     // or 'immutable_datetime'
        'payload' => 'array',
        // Optional: if your DB column is DECIMAL(10,3), keep precision here:
        // 'value'       => 'decimal:3',
    ];

    /** Relationships */
    public function device()
    {
        return $this->belongsTo(Device::class);
    }
}
